# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'webdrivers'
describe 'Veritfyitmscoachingtitle' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'veritfyitmscoachingtitle' do
    @driver.get('https://itmscoaching.com/')
    @driver.manage.window.resize_to(1552, 840)
    expect(@driver.title).to eq('iTMS Coaching | Giúp bạn trở thành Tester chuyên nghiệp')
  end
end
